name: Go_WINDOWS

on: [ push, pull_request ]

jobs:
  build:
    runs-on: windows-2022
    name: build TDengine
    steps:
      - name: checkout TDengine
        uses: actions/checkout@v2
        with:
          repository: 'taosdata/TDengine'
          ref: '3.0'

      - name: Cache cmake
        id: cache-cmake
        uses: actions/cache@v3
        with:
          path: |
            debug
            contrib/*/
          key: ${{ runner.os }}-cmake

      - name: install TDengine
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          mkdir debug && cd debug && cmake .. -G "NMake Makefiles" || cd debug
          nmake
          nmake install

      - name: Upload TDengine
        uses: actions/upload-artifact@v3
        with:
          name: TDengine
          path: C:/TDengine

  test:
    needs: build
    runs-on: windows-2022
    strategy:
      matrix:
        go: [ '1.14', '1.19' ]
    name: Go ${{ matrix.go }}
    steps:
      - name: Download TDengine
        uses: actions/download-artifact@v3
        with:
          name: TDengine

      - name: copy TDengine
        shell: cmd
        run: cp -r TDengine C:/

      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - uses: actions/cache@v3
        with:
          path: |
            ~\go\pkg\mod
          key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: run TDengine and test
        shell: cmd
        env:
          TAOS_SUPPORT_VNODES: 256
        run: |
          start /b C:/TDengine/taosd.exe > log.txt
          go test -v ./...
