name: Go_WINDOWS

on: [ push, pull_request ]

jobs:
  build:
    runs-on: windows-2022
    strategy:
      matrix:
        go: [ '1.14', '1.19' ]
    name: Go ${{ matrix.go }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: 'taosadapter'
      - name: checkout TDengine
        uses: actions/checkout@v2
        with:
          repository: 'taosdata/TDengine'
          path: 'TDengine'
          ref: '3.0'

      - name: Cache cmake
        id: cache-cmake
        uses: actions/cache@v3
        with:
          path: TDengine/debug
          key: ${{ runner.os }}-cmake

      - name: install TDengine
        shell: cmd
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          cd TDengine
          mkdir debug || true
          cd debug
          pwd
          cmake .. -G "NMake Makefiles"
          nmake
          nmake install

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - uses: actions/cache@v3
        with:
          path: |
            ~\go\pkg\mod
          key: ${{ runner.os }}-go-${{ hashFiles('taosadapter/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: run TDengine and test
        shell: cmd
        env:
          TAOS_SUPPORT_VNODES: 256
        run: |
          start /b ./TDengine/debug/build/bin/taosd.exe
          cd ./taosadapter && go test -v ./...

